name = "auroras-bloodbank"
main = ".worker-next/index.mjs"
compatibility_date = "2024-09-23"
compatibilty_flags = ["nodejs_compat"]
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }
workers_dev = true

[[d1_databases]]
binding = "DB"
database_id = "82a496e7-6efe-4a68-b282-75c9b22dce74"
database_name = "prod-auroras-bloodbank"
